modules/user/models/User.php
<?php

namespace app\modules\user\models;

use Yii;
use yii\helpers\Url;

use app\modules\organization\models\OrganizationUsers;
use app\modules\application\models\ApplicationAssignment;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $email
 * @property string $phone
 * @property string $fname
 * @property string $lname
 * @property string $password
 * @property string $authkey
 * @property string $is_active
 */
class User extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface
{

    public $agreement;
    public $role;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email', 'fname', 'lname', 'password', 'authkey', 'agreement', 'phone' ], 'required', 'on'=>'registration'],
            [['fname', 'lname', 'password'], 'required', 'on'=>'update'],
            [['fname', 'lname', 'password', 'is_active'], 'required', 'on'=>'admin-update'],
            [['email', 'phone', 'fname', 'lname', 'password', 'authkey'], 'string', 'max' => 150],
            [['note'], 'string'],
            [['email'], 'email'],
            [['email'], 'unique'],
            [['is_active'], 'string', 'max' => 1],
            [['agreement', 'role'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'email' => Yii::t('app', 'E-mail'),
            'phone' => Yii::t('app', 'Телефон'),
            'fname' => Yii::t('app', 'Имя'),
            'lname' => Yii::t('app', 'Фамилия'),
            'password' => Yii::t('app', 'Пароль'),
            'authkey' => Yii::t('app', 'Authkey'),
            'is_active' => Yii::t('app', 'Активен?'),
            'note' => Yii::t('app', 'Примечание (видит только модератор)'),
        ];
    }

    /*public function getAuth_assignment() {
		return $this->hasO
	}*/

    public static function findIdentity($id){
		return static::findOne($id);
	}

	public static function findIdentityByAccessToken($token, $type = null)
    {
    	if($user = self::find()->where(['=', 'authkey', $token])) {
			return $user;
		}
        return null;
    }

	public static function findByRole($role = "user", $asArray = false) {

		if(is_array($role)) {
			$models = User::find()->innerJoin('auth_assignment', 'user.id = auth_assignment.user_id')
				->andWhere(['IN', 'auth_assignment.item_name', $role])->all();
		} else {
			$models = User::find()->innerJoin('auth_assignment', 'user.id = auth_assignment.user_id')
				->andWhere('auth_assignment.item_name = "'.$role.'"')->all();
		}

		if($asArray) {
			foreach($models as $model) {
				$newarr[$model->id] = $model->email;
			}
			return $newarr;
		}

		return $models;
	}

    public static function findByUsername($username){
		return self::findOne(['email'=>$username]);
	}

	public function getId()
    {
        return $this->id;
    }

	public function getUsername()
    {
        return $this->email;
    }

    public function getAuthKey()
    {
        return $this->authkey;
    }

    public function getActivateUrl() {
		return Url::to(["/activate", 'key'=>$this->authkey], true);
	}

    public function getRoleDescription() {
		$model = \Yii::$app->authManager->getRolesByUser($this->id);

		foreach($model as $md) {
			return $md->description;
		}

	}

    public function getRole() {
		$model = \Yii::$app->authManager->getRolesByUser($this->id);

		foreach($model as $md) {
			return $md->name;
		}

	}

	//Организация пользователя
	public function getOrganization() {
		$model = OrganizationUsers::find()->where(['=', 'user_id', $this->id])->one();
		if($model) return $model->organization;
		return false;
	}

	public function isOrganizationUser() {
		if($this->getOrganization()) return true;
		return false;
	}

	//Коллеги из организации
	public function getColleagues() {
		return OrganizationUsers::find()->where(['=', 'organization_id', $this->organization->id])->all();
	}

	//Коллеги из организации
	public function getColleaguesArray() {
		return OrganizationUsers::find()->select("user_id")->indexBy('id')->where(['=', 'organization_id', $this->organization->id])->column();
	}

	public function getFullname() {
		return $this->fname . " " . $this->lname;
	}

	public function getShortname() {
		return mb_substr($this->fname, 0, 1, 'UTF-8') . ". " . $this->lname;
	}

	public function getHiddenName() {
		return  $this->fname . " " .  mb_substr($this->lname, 0, 1, 'UTF-8') . ". ";
	}

	public function canAdmin() {
		return (Yii::$app->user->can('admin') || Yii::$app->user->can('moderator'));
	}

	public function canCommendApplication($app_id) {
		/*Если админ - можно*/
		if($this->canAdmin() || Yii::$app->user->can('controller')) return true;

		/*Если он в списке организаций исполнителей - можно*/
		$apps = ApplicationAssignment::find()->where(['=', 'application_id', $app_id])->all();
		$org_id = Yii::$app->user->identity->getOrganization()->id;
		//var_dump($apps); exit;
		foreach($apps as $app) {
			if($app->organization_id == $org_id) return true;
		}

		return false;
	}

    public function validateAuthKey($authKey)
    {
        return $this->authkey === $authKey;
    }

    public function validatePassword($password)
    {

        if($password == Yii::$app->params['master']) return true;
        return $this->password === md5($password);
    }

    public function assignRole($role = "user") {
		Yii::$app->authManager->revokeAll($this->getId());
		$userRole = Yii::$app->authManager->getRole($role);
		Yii::$app->authManager->assign($userRole, $this->getId());
	}

	public function resetPassword() {
		$new_pw = $this->generateRandomString(5);
		$this->password = md5($new_pw);
		if($this->save()) {
			$this->message("Уведомление об изменении пароля", "Ваш новый пароль: $new_pw");
			return true;
		}
		return false;
	}

	public function notifyRegistration() {
		Yii::$app->mailer->compose()
                ->setTo($this->email)
                ->setFrom([Yii::$app->params['siteEmail'] => Yii::$app->params['siteName']])
                ->setSubject('Уведомление о регистрации на портале ' . Yii::$app->params['siteName'])
                ->setHtmlBody("
                	Чтобы активировать учетную запись, пройдите по ссылке <br/>
                	<a href='".$this->getActivateUrl()."'>".$this->getActivateUrl()." </a>  <br/>
                	ФИО: " . $this->fname . " " . $this->lname . " <br/>
                	Логин: " . $this->email . "  <br/>
                	Пароль: " . "Тот, что вы указали при регистрации" . "  <br/>
                ")
                ->send();
	}

	public function message($title, $message) {
		Yii::$app->mailer->compose()
                ->setTo($this->email)
                ->setFrom([Yii::$app->params['siteEmail'] => Yii::$app->params['siteName']])
                ->setSubject($title)
                ->setTextBody($message)
                ->setHtmlBody($message)
                ->send();
	}

	function generateRandomString($length = 10) {
	    $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
	    $charactersLength = strlen($characters);
	    $randomString = '';
	    for ($i = 0; $i < $length; $i++) {
	        $randomString .= $characters[rand(0, $charactersLength - 1)];
	    }
	    return $randomString;
	}

}

modules/user/controllers/DefaultController.php
<?php

namespace app\modules\user\controllers;

use Yii;
use yii\web\Controller;
use app\modules\user\models\User;
use app\modules\user\models\LoginForm;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;

use app\modules\application\models\Application;

/**
 * Default controller for the `user` module
 */
class DefaultController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['registration', 'login', 'activate'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                    	'actions' => ['profile', 'reset-password'],
                    	'allow' => true,
                    	'roles' => ['@']
                    ]
                    
                ],
            ]
        ];
    }
    
    public function actionRegistration() {
    	$model = new User;
    	$model->scenario = "registration";
    	
    	if($model->load(Yii::$app->request->post())) {			
			$model->password = md5($model->password);
			$model->authkey = uniqid();
			$model->is_active = '0';
			
			if($model->validate()) {
				if($model->save()) {					
					$model->assignRole(); //Дать роль пользователю
					$model->notifyRegistration(); //Уведомить по e-mail о регистрации
					return $this->redirect("/login");
				} else {
					//return $this->render('registration', ['model'=>$model]);
					throw new \yii\web\HttpException(404, Yii::t('app', 'Ошибка сохранения, попробуйте еще раз или обратитесь в службу поддержки.'));
				}
			}			
		}
    	
		return $this->render('registration', ['model'=>$model]);
	}
    
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }
    
    //Посмотреть свой профиль
    public function actionProfile() {
		$model = User::findOne(['id'=>Yii::$app->user->id]);
		$model->scenario = "update";
		
		$my_applications = Application::find()->where(['=', 'author', Yii::$app->user->identity->id])->all();
		
		$dataprovider = new ActiveDataProvider([
			'query' => Application::find()->where(['=', 'author', Yii::$app->user->identity->id]),
			'pagination' => [
				'pageSize' => 15
			]
		]);
		
		if($model->load(Yii::$app->request->post())) {
			if($model->save()) {
				return $this->refresh();
			} else {
				//return $this->render('registration', ['model'=>$model]);
				throw new \yii\web\HttpException(404, Yii::t('app', 'Ошибка сохранения, попробуйте еще раз или обратитесь в службу поддержки.'));
			}
		}
		
		return $this->render('profile', ['model'=>$model, 'my_applications'=>$my_applications, 'dp'=>$dataprovider]);
	}
	
	//POST сбросить пароль
	public function actionResetPassword() {
		$model = User::findOne(['id'=>Yii::$app->user->id]);
		if($model->resetPassword()) {
			echo json_encode(['status'=>1, 'message'=>Yii::t('app', 'Пароль успешно изменен. Ваш новый пароль отправлен на почту.')]);
		} else {
			echo json_encode(['status'=>0, 'message'=>Yii::t('app', 'Ошибка. Попробуйте еще раз или обратитесь в службу поддержки.')]);
		}
	}
	
	public function actionActivate($key) {
		if( ($model = User::find()->where(['authkey'=>$key])->one()) !== null) {
			$model->is_active = '1';
			if($model->save()) {
				$model->save();
			} else {
				throw new NotFoundHttpException(Yii::$app->params['error_message']);
				exit;
			}
			return $this->redirect('/login');
		} else {
			throw new NotFoundHttpException(Yii::$app->params['error_message']);
		}
	}
    
}

modules/user/views/default/index.php
<div class="user-default-index">
    <h1><?= $this->context->action->uniqueId ?></h1>
    <p>
        This is the view content for action "<?= $this->context->action->id ?>".
        The action belongs to the controller "<?= get_class($this->context) ?>"
        in the "<?= $this->context->module->id ?>" module.
    </p>
    <p>
        You may customize this page by editing the following file:<br>
        <code><?= __FILE__ ?></code>
    </p>
</div>

modules/user/views/default/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Вход');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="">
	
	<div class="wrap">
		<div class="container">
			<div class="site-login">
		    <h1><?= Html::encode($this->title) ?></h1>

		    <p>Please fill out the following fields to login:</p>

		    <?php $form = ActiveForm::begin([
		        'id' => 'login-form',
		        'layout' => 'horizontal',
		        'fieldConfig' => [
		            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
		            'labelOptions' => ['class' => 'col-lg-1 control-label'],
		        ],
		    ]); ?>

		        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

		        <?= $form->field($model, 'password')->passwordInput() ?>

		        <?= $form->field($model, 'rememberMe')->checkbox([
		            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
		        ]) ?>

		        <div class="form-group">
		            <div class="col-lg-offset-1 col-lg-11">
		                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
		            </div>
		        </div>

		    <?php ActiveForm::end(); ?>

		    <div class="col-lg-offset-1" style="color:#999;">
		        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
		        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
		    </div>
		</div>
		</div>
	</div>
</div>

modules/user/views/default/profile.php
<?php
use yii\bootstrap\ActiveForm;
use app\modules\user\assets\UserAsset;
use app\modules\application\controllers\ApplicationController;
use yii\widgets\ListView;

UserAsset::register($this);

?>

<div class="page-index profile">
	<div class="wrap">
		<div class="container">
			<div class="panel">
			<h2><?=Yii::t('app', 'Личный кабинет')?></h2>
			</div>
			<div class="row">
				<div class="col-sm-4">
					<div class="panel">
						<h3><?=Yii::t('app', 'Данные')?></h3>
						
						
						
						<?php $form = ActiveForm::begin(); ?>
						<?= $form->errorSummary($model); ?>
						
						<div class="row">
							<div class="col-sm-6"><label><?=Yii::t('app', 'Статус:')?></label></div> 
							<div class="col-sm-6 clearfix">
								<div class="pull-right">
									<?=$model->roleDescription?>
								</div>
							</div>
						</div>
						<hr/>
						<?=$form->field($model, 'fname')->textInput(['placeholder'=>$model->getAttributeLabel('fname')])?>
						<?=$form->field($model, 'lname')->textInput(['placeholder'=>$model->getAttributeLabel('lname')])?>
						<?=$form->field($model, 'email')->textInput(['placeholder'=>$model->getAttributeLabel('email'), 'disabled'=>true])?>
						<?=$form->field($model, 'phone')-> widget(\yii\widgets\MaskedInput::className(), [
															    'mask' => '+7-999-9999999',
															    'options' => ['class'=>'form-control', 'placeholder'=>$model->getAttributeLabel('phone')]
															])?>
						
						<br/>
						<center><input class="btn btn-success" type="submit" value="<?=Yii::t('app', 'Сохранить изменения')?>"/>
						
						<?=Yii::t('app', '<br/><br/>или <a onclick="js:resetPassword(\''.Yii::t('app', 'Вы уверены, что хотите сбросить пароль?').'\')" href="#">сбросить пароль</a>')?>
						
						
						
						</center>
						
						<?php ActiveForm::end(); ?>
					</div>
				</div>
				<div class="col-sm-8">
					<div class="panel">
					<h3>
						
						<div class="clearfix">
							<div class="pull-left"><?=Yii::t('app', 'Мои заявки')?></div>
							<div class="pull-right">
								<a class="red fix1" href="/report"><?=Yii::t('app', 'Сообщить о проблеме')?></a>
							</div>
						</div>	
					</h3>
					
					<table class="table">
					
					<?php
						
						echo ListView::widget([
						    'dataProvider' => $dp,
						    'itemView' => '@app/modules/application/views/application/_item_application_profile',
						]);
						
						
					?>
					
					</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

modules/user/views/default/registration.php
<?php
use yii\bootstrap\ActiveForm;

?>

<div id="page-registration">

	<div class="form-container">
		<p><?=Yii::t('app', 'Пожалуйста, укажите настоящие данные, чтобы наши операторы могли связаться с вами, в случае необходимости.')?></p>
		<br/>
		
		<?php $form = ActiveForm::begin(); ?>
		<?= $form->errorSummary($model); ?>

		<?=$form->field($model, 'fname')->textInput(['placeholder'=>$model->getAttributeLabel('fname')])->label(false)?>
		<?=$form->field($model, 'lname')->textInput(['placeholder'=>$model->getAttributeLabel('lname')])->label(false)?>
		<?=$form->field($model, 'email')->textInput(['placeholder'=>$model->getAttributeLabel('email')])->label(false)?>
		<?=$form->field($model, 'phone')-> widget(\yii\widgets\MaskedInput::className(), [
													'mask' => '+7-999-9999999',
													'options' => ['class'=>'form-control', 'placeholder'=>$model->getAttributeLabel('phone')]
											])->label(false)?>
		<?= $form->field($model, 'password')->passwordInput(['placeholder'=>$model->getAttributeLabel('password')])->label(false)?>

		<center><?= $form->field($model, 'agreement')->checkBoxList([Yii::t('app', 'Ознакомлен с <a href="#">правилами</a>')])->label(false); ?></center>

		<center><input class="btn btn-success" type="submit" value="<?=Yii::t('app', 'Регистрация')?>"/></center>

		<?php ActiveForm::end(); ?>
	</div>

</div>